### PR TITLE
Header update

### PR DESCRIPTION
**Pull request by sarah-avila**

### CODE REVIEW

**Review by tim-nguyen-cs — CHANGES_REQUESTED** [review]
I think it looks good. Here are a few things I noticed:

- Can you explicitly import the font family that we're using? It's loading properly on my end.
- It looks like the Material UI Button component isn't being implemented correctly because of the `class="register"` attribute. React applies classes slightly differently, so do you think you can adjust this? I also think we can forego some of the Figma design in favor for the Material UI design too.
- Instead of scaling the section, do you think we can wrap "GraceHacks", the date, and the button based on the screen resolution? I'm thinking this might look better.

**Comment by tim-nguyen-cs** [comment]
So, I"m realizing that the customization the Button is harder than expected, so we can either comply to Material's UI, so all our buttons look the identical or customize them ourselves using React classes. 

What do you think we should do?

**Comment by sarah-avila** [comment]
@tim-nguyen-cs Looking at the Figma design, it looks like the only buttons on the entire website are the header "register" button, the navbar links, and the social media buttons (are there any others I'm forgetting?). Since they all look different design-wise, would it be better to customize these buttons using React classes? Unless customization is difficult to implement... Let me know what you think!

**Comment by tim-nguyen-cs** [comment]
I think for the "Register" buttons, we can use the same (default) component styles, but we can leave the navigation bar and social media buttons as is. What do you think?

**Comment by sarah-avila** [comment]
@tim-nguyen-cs Okay! So just to clarify, when you say "leave as is" for the navbar and social media buttons, do you mean to not make them Material UI Buttons and leave them as divs?

**Comment by sarah-avila** [comment]
@tim-nguyen-cs Hi Tim! I made some changes to the header component, but I had a question about how the mobile version should look. I was playing around with it a bit and tried my best to match the Figma. I don't think I can wrap the "gracehacks" because the logo can't be expanded vertically, so would you prefer the "gracehacks" to stay in line but have the date and register button wrap below the logo? Or I could try and fix this version so that the button is smaller but the data and button stay in the same place. Let me know if I can clarify anything!

**Comment by tim-nguyen-cs** [comment]
@sarah-avila Oh, I see what's going on - so, right now it looks like all the elements (image, title, date, button) are aligned in one column with a large negative top margin to align things. Do you think we can instead create two columns, each aligned horizontally (two axes total)? We'll only need a negative margin on the "UCSC" text and can use `flex-wrap: wrap` to wrap the rightmost column underneath the logo when the screen gets smaller.

IMO, the logo should be left-aligned, but that up to you! :D

**Comment by sarah-avila** [comment]
@tim-nguyen-cs I followed your suggestion and created two columns so when the screen size shrinks the "gracehacks", date, and register button wrap beneath the logo. Is this what you had in mind?

**Comment by tim-nguyen-cs** [comment]
@sarah-avila Yep! That's exactly what I was imaging - let me know if this works or if you can think of something even better!

I went in and made a few optimizations here (`ca73133`), so let me know if you have any questions about them. Otherwise, I think there's just about two things left to do:

[] - Import the Avenir font. Although I can do this, it'll be great practice - take a look at the VCR font and how I imported it earlier as an example
[] - Add a media query under maybe 450px to scale the header based on the current view-width. For this, I think just a straight-set scaling pattern would be fine.

**Comment by sarah-avila** [comment]
@tim-nguyen-cs Thanks for the suggestions! Let me know what you think of my changes:
- I added the font to the assets folder and added a @font-face to the App.scss file. Is this what you meant by explicitly importing the font?
- I edited the mobile version to include a media query, but didn't exactly scale it using percentages. I like this implementation in my latest commit because you can see the entire header at any window size, but let me know if you would prefer the scaling. I also tried to make the button longer in the mobile version but couldn't seem to implement a custom breakpoint successfully (the button switches too early when shrinking the window size). Would you know how to fix this custom breakpoint?

Let me know if you have any questions!

**Comment by tim-nguyen-cs** [comment]
@sarah-avila Awesome, thanks for working on that. I honestly think it looks great, so it looks pretty much ready to go. Going of your question about custom breakpoints, there are some things that I noticed:
- Your breakpoint at 1100 pixels looks like it works correctly, because you used `@media only screen and (max-width: 1100px)` in the `*.scss` file - at the end of the day, it's just native CSS at this point, so the media queries works well.
- I saw that you created a custom them with a large breakpoint at 900 pixels. If you wanted to override the default breakpoints, I think this is a great way to do it, but I do think it's being used correctly. If you inspect the responsiveness, it still breaks at around 1200px, so that theme isn't being applied correctly when used in `useStyles(theme)`.

I think all we have to do is decrease the font-size of the "GraceHacks" so the title on the "Moto G4" doesn't look so cramped and clean up the media queries a bit so it's ready for production. I'll be happy to help you out with this, but let me know how it goes!

**Comment by sarah-avila** [comment]
@tim-nguyen-cs Thanks for catching that responsiveness issue! I fixed the custom breakpoint problem and cleaned up the code, so I think this looks good to go! Let me know if there's anything else I can do for this header!

**Comment by tim-nguyen-cs** [comment]
Looks great! Went in and did some formatting things, but we can get this in now!

**Pull request merged**
