### PR TITLE
revised navigation for desktop view

### PR DESCRIPTION
**Pull request by tim-nguyen-cs**
Revised desktop version! If this look good, I can work on the mobile version next!

### CODE REVIEW

**Comment by sarah-avila** [comment]
@tim-nguyen-cs The navbar looks great! I have one small concern about the readability of the "register" button since both the button and the text are light-colored, but I'll leave that decision up to you. I will also design the header "register" button following your design choice. Thanks for working on this!

**Comment by tim-nguyen-cs** [comment]
@sarah-avila Woahh, thanks for catching that! I forgot to apply the class I made to the button - it should be good now.

I also added a menu for the mobile design, so let me know if it looks good to you! If so, this should be all ready to go!

**Comment by sarah-avila** [comment]
@tim-nguyen-cs The mobile menu looks really good! I just double checked the Figma and I quickly changed 'Sponsor' to 'Sponsors' in both the desktop and mobile version. I also made a small suggestion to the logo placement in the mobile version by making the left margin a percentage to decrease the space of the left of the logo. I kept your changes commented out so you can compare them, but once you choose between those two options, I think this is all set to go!

**Comment by tim-nguyen-cs** [comment]
@sarah-avila Awesome, I think your changes look great!

**Pull request merged**
